### ISSUE TITLE
Accessing areChildrenDirty causes Uncaught TypeError

### ISSUE THREAD

**Issue by jonahgeorge** [lolmaus/ember-cli-stained-by-children#1]
Following the instructions in the README, receiving a `Uncaught TypeError: undefined is not a function` in [mixin.js](https://github.com/lolmaus/ember-cli-stained-by-children/blob/0.x/addon/mixin.js#L74) line #74 when attempting to access `areChildrenDirty` and consequently `isDirty`.

Using:
- ember 1.9.1 and 1.8.1
- ember-data 1.0.0-beta.12

``` javascript
// app/models/student.js
import DS from 'ember-data';
import StainedByChildrenMixin from 'stained-by-children/mixin';

export default DS.Model.extend(StainedByChildrenMixin, {
  gender: DS.belongsTo('gender', { async: true, stains: true }),
  stage: DS.belongsTo('stage', { async: true, stains: true })
  // other attributes
});
```

**Comment by lolmaus** [comment]
Thank you for reporting!

It turned out that i had only implemented support for `hasMany` relationships.

I've implemented support for `belongsTo` relationships.

I've also fixed a bug crashing the app on empty relationships.

It should work now. Please try and report! I will reopen the ticket if your issues persist.

PS Also added a note that circular references are not supported.

**Comment by lolmaus** [comment]
Fixed with c4428f1, released as `0.2.0`.

**Comment by jonahgeorge** [comment]
Yup, looks like everything is working now. Thanks!

**Comment by lolmaus** [comment]
Thank you for your feedback.

I would really appreciate if you starred this addon on Github and spread the word. ^_^
