### ISSUE TITLE
How to install and use?

### ISSUE THREAD

**Issue by sn3p** [lolmaus/ember-cli-stained-by-children#16]
How do I **install and use** the latest version ([gen-3](https://github.com/lolmaus/ember-cli-stained-by-children))?
The readme in Git differs form the NPM module readme.

**Comment by lolmaus** [comment]
Hey @sn3p. This addon is not actively developed. That's due to the fact that I personally don't need this functionality in any of my current projects, and I don't have a user that would actively help me test it (mostly by kicking me daily to make me spend some time on it).

`gen-3` is not complete and thus hasn't been published on npm. You can try it out by installing from GitHub:

```
npm i -D lolmaus/ember-cli-stained-by-children#gen-3
```

(Note that for production use you should never depend on a branch. Always depend on a specific commit.)

Feel free to start punching me (I'm available on Gitter and on Ember Slack) to have this finished and released.

PS I'm closing this, but you're welcome to continue the discussion here.
