### ISSUE TITLE
Replacing a non-dirty child with another non-dirty child does not make the parent dirty

### ISSUE THREAD

**Issue by jonahgeorge** [lolmaus/ember-cli-stained-by-children#2]
I haven't looked into how difficult this would be, but it would be nice to set the `isDirty` flag when `model.content` is changed.
##### Use Case

This is especially applicable when using Ember.Select to set associated records. The current way of working with Select is to set `selection=model.content` rather than `model`; however, this means the `isDirty` flag is never set to true.

**Comment by lolmaus** [comment]
Hey @jonahgeorge, thank you for your interest in my humble addon. This is my first contribution to the Ember community and i'm very excited that someone is actually using it.

I'd be very happy if you starred the project (do it now! :smile:).

As for your question, i think, you're misusing `Ember.Select`. I've never used it before, but i have fixed up a small example. Please, have a look: http://emberjs.jsbin.com/yetoyu/2/edit?html,js,output

As you see, `Ember.Select` has nothing to do with `model.content`. Maybe you have confused it with the [`content` property](http://emberjs.com/api/classes/Ember.Select.html#toc_the-content-property-array-of-objects) of the select view?

The only other built-in `content` property i'm aware of is [that of DS.ManyArray](http://emberjs.com/api/data/classes/DS.ManyArray.html#property_content). The property stores an array of ids. It makes no sense to pass it as the `selection` property to the select view, because the `selection` property should contain a single record, not an array of ids.

If your `model.content` is a custom property on a model, then simply make it either a `DS.attr()` or a `DS.hasMany()`/`DS.belongsTo` with `{stains: true}`, and it will stain the record automatically.

If this doesn't help, please provide a JSBin example of your situation. StainedByChildren is not yet available for JSBin, but i'm [working on it](http://stackoverflow.com/questions/27999488/how-do-i-split-my-ember-cli-addon-into-a-vanilla-ember-library-and-an-ember-cli).

**Comment by lolmaus** [comment]
Oh, you're the same guy that made me make the addon actually work. Cheers!

**Comment by lolmaus** [comment]
I've investigated your issue further and discovered that `DS.ManyArray` does not actually have a `content` property. It was a [bug in documentation](https://github.com/emberjs/data/pull/2709).

So what `model.content` are you talking about?

**Comment by jonahgeorge** [comment]
Here's a [jsbin](http://emberjs.jsbin.com/valinomude/2/edit?html,js,output) demonstrating what I mean. I apologize for the large block of text in the js tab, I was having issues getting the addon to work.

You can see that when using the Ember.Select view, setting `selection=gender.content` does not update the `isDirty` flag (even when `stains: true` is set).

**Comment by lolmaus** [comment]
I finally got to look at your issue, sorry for the delay.

Your issue is completely different from what `StainedByChildren` currently does. It has nothing to do with the `content` property (which comes from a `PromiseObject`, by the way).

You want the parent record to become dirty whenever its relationship is modified (e. g. a related object is replaced with another).

Currently `StainedByChildren` does not address that use case. `StainedByChildren::areChildrenDirty` only monitors the `isDirty` state of a child, and when you change one non-dirty child with another non-dirty child, the result is non-dirty.

I wish `StainedByChildren` could handle your use case, but i've got no idea how. I don't understand how to distinguish a modified relationship from an initially set up one. If you observe a `child` or `children.[]` path on a parent model, the observer will be triggered twice on record creation.

Unless you suggest something clever, the only solution i see is to stain the parent manually from user-generated actions that cause the parent's relationships to change. E. g. you modify a gender of a user _and_ you mark that user dirty manually (`user.send('becomeDirty')`).

FYI, this issue is planned to be addressed in Ember Data. It is currently tracked in this meta issue: https://github.com/emberjs/data/issues/2545 and this RFC: https://github.com/emberjs/rfcs/pull/21 .

**Comment by metanoic** [comment]
@jonahgeorge Unfortunately the advice you got about using .content from your async relationship's proxy for your binding was erroneous.  It works fine for read-only, but when the select value is changed, it's just going to .set("relationship.content", value) rather than .set("relationship", value) - thereby bypassing the relationship's addRecord() method and never updating the internal manyArray (hasMany) or inverseRecord (belongsTo).

Look in to using a computed property that wraps the get/set of your relationship while always returning a PromiseObjectProxy (mixin PromiseProxy and ObjectProxy) and drop the .content from your binding and let the proxy do its job.

**Comment by lolmaus** [comment]
This is a use-case i would like `stained-by-children` to address.

**Comment by Kerrick** [comment]
It could be useful to have hasMany relationships compare the ManyArray's currentState to its canonicalState, but for belongsTo you'd have to read `_data`, which I think is a no-no.

**Comment by miguelcobain** [comment]
Just for completeness, there's this code: http://paulferrett.com/2014/ember-model-isdirty-when-belongsto-changes/
which does read `_data`, like @Kerrick said.

@Kerrick, is there any particular reason we shouldn't use `_data`, besides being private API?

**Comment by justin-hackin** [comment]
@miguelcobain _data is now deprecated.

In order to get past this issue, I modified the code (and CleanEmbeddedRecordMixin) provided here as follows  http://pastebin.com/x33Cukf3 (works with Ember 2.0) .  Then your belongsTo relationship must contain a trackDirt: true option.  Not sure if it will work for all cases, but it seems to be doing the trick ...

**Comment by alexanderjeurissen** [comment]
@lolmaus @justin-hackin is there any chance we could get these changes in a pull request ?, i see you  use coffee script so compiling it first would be necessary. we could of course use the pastbin you provided but rather use an updated version of this add-on that incorporates your change set.

**Comment by lolmaus** [comment]
@alexanderjeurissen I'm available for discussion and some work, but I gave up on this addon already. If you tell me what to do specifically, I'll do it.

PS It should be JS now, not CoffeeScript.

**Comment by alexanderjeurissen** [comment]
I copied the pastebin of @justin-hackin and compiled it to JS (since his pastebin is in coffeescript) I'm going to test if all works correctly. If it does then I'll cleanup the code and open a pullrequest.

**Comment by lolmaus** [comment]
Ah, it's @justin-hackin's code that's CoffeeScript. The addon also started with CoffeeScript but then I rewrote it, that's why I got confused. :)

**Comment by lolmaus** [comment]
@alexanderjeurissen Can you please also include tests in the PR?

**Comment by alexanderjeurissen** [comment]
@lolmaus How about defining a volatile computed property that is called recursively on all `belongsTo` relationships that contain the `stains` option ? sure it's a bit more memory intensive but how often do we find models that have a depth of > 5

i was thinking about something like this:

``` javascript
import Ember from 'ember';

var StainedByChildrenMixin = Ember.Mixin.create({
  isFilthy: Ember.computed(function() {

    if (this.get('hasDirtyAttributes')) {
      return true;
    }

    var self = this, dirty = false;

    this.eachRelationship(function(name, relationship) {
      if (dirty) return;
      if (relationship.kind === 'belongsTo' && relationship.options.stains) {
        var child = self.get(name);
        dirty = !!child && child.get('isFilthy');
      }
    });

    return dirty;
  }).volatile()
});

export default StainedByChildrenMixin;
```

**Comment by alexanderjeurissen** [comment]
the other downside besides the increased memory usage is ofc that it can't be cached and thus needs to be calculated every time you need to know the dirty state.

**Comment by alexanderjeurissen** [comment]
ok the above code doesn't work this code snippet does:

``` javascript
import Ember from 'ember';

var StainedByChildrenMixin = Ember.Mixin.create({
  isFilthy: function() {
    if (this.get('hasDirtyAttributes')) {
      return true;
    }

    var dirty = false,
      self = this;

    this.eachRelationship(function(name, relationship) {
      var model = self.get(name)

      if (dirty || !model || !relationship.options.stains) {
        return;
      }

      if (relationship.kind === 'hasMany') {
        dirty = model.isAny('isFilthy', true);
      } else if (relationship.kind === 'belongsTo') {
        dirty = model.get('isFilthy');
      }
    });

    return dirty;
  }.property().volatile()
});

export default StainedByChildrenMixin;
```

**Comment by alexanderjeurissen** [comment]
@lolmaus what's your opinion of this approach ? I've copied some of the model specs you use and rewrote them to use models of my own app. which has the following model hierarchy:
 `quiz` belongs to `chapter`
`quiz` has many `questions`
`question` has many `answer options`

the above computed property works with that scenario, changing something in an answer option will render it's parents `dirty`

**Comment by alexanderjeurissen** [comment]
@lolmaus is this kind of implementation something your interested in ? currently I'm using it in our app and it at least fixes the stainedByChildren mixin.. I would love to write a PR and use this add-on instead though ;)

**Comment by lolmaus** [comment]
@alexanderjeurissen, I believe we should start from scratch. It will be much simpler than trying to update this addon.

I'll try to find time this weekend to create a new addon boilerplate (in another branch) and implement some failing tests.

**Comment by alexanderjeurissen** [comment]
I understand and agree, I wrote my solution from scratch as well. 
this is the currently working version (I'll paste it here maybe it can be a starting point for your rework):

``` javascript
import Ember from 'ember';

var StainedByChildrenMixin = Ember.Mixin.create({
  isFilthy: function() {
    if (this.get('hasDirtyAttributes')) {
      return true;
    }

    var dirty = false,
      self = this;

    this.eachRelationship(function(name, relationship) {
      var model = self.get(name)

      if (dirty || !model || !relationship.options.stains) {
        return;
      }

      var relationshipType = relationship.kind;
      var dirtyKey = _hasProperty(model, 'isFilthy') ? 'isFilthy'
                                                     : 'hasDirtyAttributes';
      if (relationshipType === 'hasMany') {
        dirty = model.isAny(dirtyKey, true);
      } else if (relationshipType === 'belongsTo') {
        dirty = model.get(dirtyKey);
      }
    });

    return dirty;
  }.property().volatile()
});

function _hasProperty(model, property) {
  if (model instanceof DS.ManyArray) {
    var singleInstance = model.objectAt(0)
    return singleInstance && Ember.isPresent(singleInstance[property]);
  } else {
    return Ember.isPresent(model[property]);
  }
}

export default StainedByChildrenMixin;
```

basically instead of adding observers to children, it just recursively checks the `hasDirtyAtributes` of all nested models which relationship has a `stains` flag and is of kind `belongsTo` or `hasMany`.

**Comment by lolmaus** [comment]
So I finally got my hands to it!

I've started a new branch [1.x](https://github.com/lolmaus/ember-cli-stained-by-children/tree/1.x), created a failing test and used @alexanderjeurissen's code to make the test pass.

But before this gets released, there's quite some work to be done:
1. I don't like volatile. Instead, I want to use normal computed properties. This should be possible if we inspect relationshps on `init` and dynamically define computed properties.
2. More tests! And fix Travis.
3. Implement a mixin to clean embedded children when parent is saved.
4. Implement a mixin to delete embedded children when parent is deleted.

I'm happy this finally got traction. Please excuse me it took me so long.

PS Frequent pokes are welcome to keep me working. I easily get distracted. :grin:

**Comment by alexanderjeurissen** [comment]
@lolmaus Nice i saw your commit ;)

I also fixed the CleanEmbedded mixin, if you want I can share that code as well.

The `_attributes` is still present, but is now nested inside the _internalmodel property of a model.

code:

``` javascript
import Ember from 'ember';

var CleanEmbeddedRecordsMixin = Ember.Mixin.create({
  save: function() {
    return this._super().then(function() {
      _cleanEmbeddedModels(this);
      this.reload();
    }.bind(this))
  },

  rollbackAttributes: function() {
    this._traverseChildren(function(model, relationship) {
      if (!relationship.options.cascadeRollback) return;
      model.rollbackAttributes();
    });

    return this._super();
  },

  _traverseChildren: function(callback) {
    this.eachRelationship(function(name, relationship) {
      var model = this.get(name);

      if (!model) return;

      switch (relationship.kind) {
        case 'hasMany':
          model.forEach(function(child) {
            callback(child, relationship);
          });
          break;
        case 'belongsTo':
          callback(model, relationship);
          break;
      }
    }.bind(this))
  }
});

function _cleanEmbeddedModels(model, relationship) {
  if (relationship && !relationship.options.cleanEmbedded) return;

  model.send('willCommit');

  if (model.get('hasDirtyAttributes')) {
    model.set('_internalModel._attributes', {});
  }

  model.send('didCommit');

  if (typeof model._traverseChildren === 'function') {
    model._traverseChildren(_cleanEmbeddedModels)
  }
}

export default CleanEmbeddedRecordsMixin;
```

**Comment by lolmaus** [comment]
Tests fail on Beta and Canary. This is not good. I'll look into it tomorrow.

**Comment by alexanderjeurissen** [comment]
hmm that's interesting, keep me in the loop !

**Comment by alexanderjeurissen** [comment]
@lolmaus did you find time to test the implementation any further ? do you need any help with this ? I may have some time next saturday.

**Comment by lolmaus** [comment]
@alexanderjeurissen Nope, got distracted with other pet projects.

How about we pair up on Saturday? Need to agree on time and prepare the agenda.

**Comment by alexanderjeurissen** [comment]
@lolmaus sounds good to me ! what timezone are you at ? and we should probably exchange skype / contact info through email, mine is: `alexanderjeurissen@gmail.com`

**Comment by kimroen** [comment]
Poke! ^_^

**Comment by lolmaus** [comment]
@kimroen, me and @alexanderjeurissen have started a new branch from scratch: https://github.com/lolmaus/ember-cli-stained-by-children/tree/1.x

It's a work in progress and currently only the main `stained-by-children` mixin is implemented: https://github.com/lolmaus/ember-cli-stained-by-children/blob/1.x/addon/stained-by-children.js

I'm not in need for this functionality in my current projects and thus I'm not actively developing it. If you're very persistent in poking me (hint: use Gitter for realtime poking), I can do more work. Also consider setting up a pair programming session.
